/** Open a printable A4 HTML window for the document and trigger Save as PDF. */
export function openPrintablePdf(opts: {
  title: string;
  kind: string;
  body: string;
  recipient?: string;
  issuedAt?: string;
}) {
  const issued = opts.issuedAt ?? new Date().toISOString().slice(0, 10);
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(opts.title)}</title>
<style>
@page{size:A4;margin:24mm}
*{box-sizing:border-box}
body{font-family:-apple-system,Segoe UI,Inter,sans-serif;color:#0b1730;line-height:1.6;margin:0;padding:32px}
.hdr{display:flex;justify-content:space-between;align-items:flex-end;border-bottom:2px solid #0b1730;padding-bottom:14px;margin-bottom:28px}
.brand{font-weight:800;letter-spacing:.18em;color:#0b1730;font-size:14px}
.sub{font-size:10px;color:#5b6478;letter-spacing:.2em;text-transform:uppercase;margin-top:4px}
.meta{font-size:11px;color:#5b6478;text-align:right}
h1{font-size:22px;margin:0 0 6px;letter-spacing:-.01em}
.kind{font-size:10px;color:#3258d6;letter-spacing:.24em;text-transform:uppercase;font-weight:700}
.body{white-space:pre-wrap;font-size:13px;margin-top:18px}
.sig{margin-top:60px;display:flex;justify-content:space-between;font-size:11px;color:#5b6478}
.sig div{border-top:1px solid #c4cad8;padding-top:6px;width:40%}
.foot{position:fixed;bottom:14mm;left:24mm;right:24mm;font-size:9px;color:#9098a8;letter-spacing:.16em;text-transform:uppercase;text-align:center;border-top:1px solid #eef0f4;padding-top:6px}
@media print{.noprint{display:none}}
</style></head><body>
<div class="hdr">
  <div><div class="brand">WASL</div><div class="sub">by Humanai · AI-powered HR</div></div>
  <div class="meta">Issued ${issued}<br/>Ref WSL-${Math.random().toString(36).slice(2,8).toUpperCase()}</div>
</div>
<div class="kind">${escapeHtml(opts.kind)}</div>
<h1>${escapeHtml(opts.title)}</h1>
${opts.recipient ? `<div style="font-size:12px;color:#5b6478;margin-top:6px">Recipient: <b style="color:#0b1730">${escapeHtml(opts.recipient)}</b></div>` : ""}
<div class="body">${escapeHtml(opts.body || "This document is generated by Wasl HR. Authorised personnel may verify its authenticity via the platform.")}</div>
<div class="sig"><div>HR Officer</div><div style="text-align:right">Authorised signature</div></div>
<div class="foot">Wasl by Humanai · Confidential HR document · Verified via platform</div>
<div class="noprint" style="position:fixed;top:8px;right:8px"><button onclick="window.print()" style="padding:6px 10px;font:600 11px sans-serif;background:#0b1730;color:#fff;border:0;border-radius:6px;cursor:pointer">Print / Save PDF</button></div>
<script>setTimeout(()=>window.print(),350)</script>
</body></html>`;
  // Use a Blob URL so the new window has a proper document & navigation
  // context — `document.write` into a blank window is blocked or rendered
  // as a blank page in many browsers (Chrome, Safari, in-app webviews).
  try {
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const w = window.open(url, "_blank", "noopener,noreferrer,width=900,height=1100");
    if (!w) {
      // Popup blocked — trigger a download fallback so the user still gets the file
      const a = document.createElement("a");
      a.href = url;
      a.download = `${opts.title.replace(/[^a-z0-9]+/gi, "_")}.html`;
      document.body.appendChild(a);
      a.click();
      a.remove();
    }
    // Revoke after a delay so the new window has time to load
    setTimeout(() => URL.revokeObjectURL(url), 60_000);
  } catch (e) {
    console.error("openPrintablePdf failed", e);
  }
}

function escapeHtml(s: string) {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));
}