import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { PageHeader, Panel, Stat } from "@/components/dashboard/Bits";
import { Modal, Toast } from "@/components/Modal";
import { FileText, Plus, Download, Loader2, BookOpen, Trash2, Sparkles } from "lucide-react";
import { createDocument, listAllDocuments } from "@/lib/documents.functions";
import { openPrintablePdf } from "@/lib/pdf";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/dashboard/rh/documents")({
  component: RHDocs,
});


const TEMPLATES: { label: string; type: "certificate"|"contract"|"policy"|"other" }[] = [
  { label: "Salary certificate", type: "certificate" },
  { label: "Leave request", type: "other" },
  { label: "Remote-work attestation", type: "certificate" },
  { label: "Internal transfer", type: "other" },
  { label: "Loan attestation", type: "certificate" },
  { label: "End-of-contract certificate", type: "certificate" },
];

function RHDocs() {
  const [open, setOpen] = useState(false);
  const [tplIdx, setTplIdx] = useState(0);
  const [emp, setEmp] = useState("");
  const [notes, setNotes] = useState("");
  const [toast, setToast] = useState<string | null>(null);
  const qc = useQueryClient();

  const listFn = useServerFn(listAllDocuments);
  const createFn = useServerFn(createDocument);
  const { data } = useQuery({ queryKey: ["all-docs"], queryFn: () => listFn() });
  const create = useMutation({
    mutationFn: (input: any) => createFn({ data: input }),
    onSuccess: ({ document }) => {
      qc.invalidateQueries({ queryKey: ["all-docs"] });
      setOpen(false); setEmp(""); setNotes("");
      setToast(`${document.title} generated`);
      openPrintablePdf({ title: document.title, kind: TEMPLATES[tplIdx].label, body: notes || "Generated by HR.", recipient: emp, issuedAt: document.issued_at ?? undefined });
    },
    onError: (e: any) => setToast(e?.message ?? "Failed"),
  });

  function submit(e: React.FormEvent) {
    e.preventDefault();
    const tpl = TEMPLATES[tplIdx];
    create.mutate({
      title: `${tpl.label} · ${emp || "Collaborator"}`,
      type: tpl.type,
      body: `Recipient: ${emp}\n\n${notes}`,
    });
  }

  const docs = (data?.documents ?? []) as any[];

  return (
    <div className="space-y-5">
      <PageHeader kicker="Documents" title="Generation queue" subtitle="AI-assisted creation, validation and dispatch of every HR document."
        right={<button onClick={()=>setOpen(true)} className="pill-btn accent !text-[10px] !py-1.5 !px-3 tracking-[0.2em] uppercase"><Plus className="w-3.5 h-3.5"/> New document</button>} />

      <div className="grid grid-cols-3 gap-2">
        <Stat label="Total" value={String(docs.length)} accent />
        <Stat label="Last 7d" value={String(docs.filter(d=>Date.now()-new Date(d.created_at).getTime()<7*864e5).length)} />
        <Stat label="Templates" value={String(TEMPLATES.length)} />
      </div>

      <Panel label="QUEUE" title="All issued documents">
        {docs.length === 0 && <div className="text-xs text-muted-foreground py-4">No documents yet.</div>}
        {docs.map((d) => (
          <div key={d.id} className="flex items-center gap-3 py-3 border-b border-border last:border-0">
            <div className="w-10 h-10 rounded-lg bg-secondary grid place-items-center"><FileText className="w-4 h-4 text-accent" /></div>
            <div className="flex-1 min-w-0">
              <div className="font-medium text-sm truncate">{d.title}</div>
              <div className="text-xs text-muted-foreground truncate">{d.owner?.full_name ?? "Unknown"} · {new Date(d.created_at).toLocaleDateString()}</div>
            </div>
            <button onClick={() => openPrintablePdf({ title: d.title, kind: d.type, body: decodeBody(d.storage_path), recipient: d.owner?.full_name, issuedAt: d.issued_at })} className="pill-btn !text-[9px] !py-1.5 !px-3 tracking-[0.2em] uppercase">
              <Download className="w-3 h-3"/> PDF
            </button>
          </div>
        ))}
      </Panel>

      <Panel label="TEMPLATES" title="Quick generate">
        <div className="grid grid-cols-1 gap-2">
          {TEMPLATES.map((t, i) => (
            <button key={t.label} onClick={() => { setTplIdx(i); setOpen(true); }}
              className="flex items-center justify-between gap-2 px-3 py-2.5 rounded-xl border border-border bg-card hover:border-foreground transition text-sm text-left">
              <span className="inline-flex items-center gap-2"><FileText className="w-4 h-4 text-accent"/> {t.label}</span>
              <Plus className="w-4 h-4 text-muted-foreground" />
            </button>
          ))}
        </div>
      </Panel>

      <EnterpriseDocsPanel onToast={setToast} />

      <Modal open={open} onClose={() => setOpen(false)} kicker="GENERATE" title="New document"
        footer={
          <button form="doc-form" type="submit" disabled={create.isPending} className="pill-btn accent w-full justify-center !py-2.5 !text-[11px] tracking-[0.2em] uppercase disabled:opacity-50">
            {create.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin"/> : "Generate & open PDF"}
          </button>
        }>
        <form id="doc-form" onSubmit={submit} className="space-y-3">
          <div>
            <div className="text-[10px] tracking-[0.22em] uppercase text-muted-foreground mb-2 font-bold">Template</div>
            <select value={tplIdx} onChange={e=>setTplIdx(Number(e.target.value))} className="w-full px-3 py-2.5 rounded-xl border border-border bg-card text-sm focus:outline-none focus:border-foreground">
              {TEMPLATES.map((t, i) => <option key={t.label} value={i}>{t.label}</option>)}
            </select>
          </div>
          <div className="field"><div className="relative">
            <input id="doc-emp" placeholder=" " value={emp} onChange={e=>setEmp(e.target.value)} required />
            <label htmlFor="doc-emp">Collaborator</label>
          </div></div>
          <div className="field"><div className="relative">
            <textarea id="doc-note" placeholder=" " rows={3} value={notes} onChange={e=>setNotes(e.target.value)} className="resize-none" />
            <label htmlFor="doc-note">Notes (optional)</label>
          </div></div>
          <div className="rounded-xl bg-secondary/60 border border-border p-3 text-[11px] text-muted-foreground leading-relaxed">
            Generates a Wasl-branded PDF, stores the record and opens print preview.
          </div>
        </form>
      </Modal>

      <Toast msg={toast} onDone={() => setToast(null)} />
    </div>
  );
}

function decodeBody(path: string | null): string {
  if (!path?.startsWith("inline://")) return "";
  try { return decodeURIComponent(escape(atob(path.slice(9)))); } catch { return ""; }
}
